name:                prosidy
version:             0.1.0.0
github:              "s-william/prosidy"
license:             BSD3
author:              "Simon Williams"
maintainer:          "simon@infeasiblesolutions.com"
copyright:           "2018 Simon Williams"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Prosidy is a programming language
# category:            Programming Languages

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/s-william/prosidy#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  prosidy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosidy

tests:
  prosidy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prosidy
